# Generated by Django 5.1.3 on 2024-11-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, choices=[('pass', 'Зачет'), ('fail', 'Не зачет')], max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('deadline', models.DateField()),
                ('level', models.IntegerField()),
                ('chapter', models.IntegerField()),
                ('clue', models.TextField()),
            ],
        ),
    ]
