# Generated by Django 5.1.3 on 2024-12-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='grade',
            field=models.CharField(blank=True, choices=[('pass', 'зачет'), ('fail', 'не зачет')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='status',
            field=models.CharField(blank=True, choices=[('sended', 'Отправлено'), ('not_sended', 'Не отправлено')], max_length=15, null=True),
        ),
    ]
