# Generated by Django 5.1.3 on 2024-12-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_grade_grade_alter_grade_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('task_id', models.IntegerField()),
                ('level', models.CharField(blank=True, max_length=255, null=True)),
                ('submission_date', models.DateField()),
                ('status', models.CharField(max_length=15)),
                ('grade', models.CharField(max_length=4)),
                ('code', models.TextField()),
            ],
            options={
                'db_table': 'journal_view',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
