# Generated by Django 5.1.3 on 2024-12-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_journalview_alter_task_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='level',
        ),
        migrations.AlterField(
            model_name='task',
            name='chapter',
            field=models.CharField(max_length=100),
        ),
    ]
