# Generated by Django 5.1.3 on 2024-12-03 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_task_level_alter_task_chapter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='name',
            new_name='level',
        ),
    ]
