# Generated by Django 5.1.3 on 2024-12-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_rename_name_task_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=4)),
                ('level', models.CharField(max_length=100)),
                ('chapter', models.CharField(max_length=100)),
                ('submission_date', models.DateField()),
                ('deadline', models.DateField()),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'newview_1',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.CharField(blank=True, choices=[('', 'Любой'), ('pass', 'зачет'), ('fail', 'не зачет')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='status',
            field=models.CharField(blank=True, choices=[('', 'Любой'), ('sended', 'Отправлено'), ('not_sended', 'Не отправлено')], max_length=15, null=True),
        ),
        migrations.AlterModelTable(
            name='journalview',
            table='newview',
        ),
    ]
