# Generated by Django 5.1.3 on 2024-12-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_task_text_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamefield',
            name='json_field',
            field=models.JSONField(default=list),
        ),
    ]
