# Generated by Django 5.1.3 on 2024-12-11 09:33

import mainapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_gamefield_json_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamefield',
            name='json_field',
            field=models.JSONField(default=mainapp.models.jsonfield_default_value),
        ),
    ]
