# Generated by Django 5.1.3 on 2024-12-11 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_gamefield_json_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamefield',
            old_name='json_field',
            new_name='data',
        ),
    ]
