# Generated by Django 5.1.3 on 2024-12-24 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_code_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='game_field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.gamefield'),
        ),
    ]
