# Generated by Django 5.1.3 on 2024-12-24 20:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_code_game_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='code',
            unique_together={('user', 'game_field')},
        ),
    ]
